export const LOAD_FRADULENT_TRANS_STARTED = "LOAD_FRADULENT_TRANS_STARTED";
export const LOAD_FRADULENT_TRANS_SUCCESS = "LOAD_FRADULENT_TRANS_SUCCESS";
export const LOAD_FRADULENT_TRANS_ERROR = "LOAD_FRADULENT_TRANS_ERROR";